[package]
name = "truth-rs-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8.6"
truth-rs-type = { path = "../truth-rs-type" }
serde_json = "1.0.108"
