name: CI

on:
  push:
    branches:
      - main
    tags:
      # Regex for a version number such as 0.2.1
      - 'v[0-9]+.[0-9]+.[0-9]+'
  pull_request:

permissions:
  contents: write

jobs:
  build-and-upload:
    name: Build and upload
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # You can add more, for any target you'd like!
        include:
          - build: linux
            os: ubuntu-latest
            target: x86_64-unknown-linux-musl

          - build: macos
            os: macos-latest
            target: x86_64-apple-darwin
          # - build: windows-gnu
          #   os: windows-latest
          #   target: x86_64-pc-windows-gnu

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          targets: ${{ matrix.target }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --verbose --release --target ${{ matrix.target }}
      - name: Build archive
        shell: bash
        run: |
          # Replace with the name of your binary
          binary_name="truth-rs"
          dirname="bin/${{ matrix.target }}"
          sudo rm -rf "$dirname"
          mkdir "$dirname"
          if [ "${{ matrix.os }}" = "windows-latest" ]; then
            mv "target/${{ matrix.target }}/release/$binary_name.exe" "$dirname"
          else
            mv "target/${{ matrix.target }}/release/$binary_name" "$dirname"
          fi
      - name: Configure Git
        run: |
          git config --global user.email 3434909403@qq.com
          git config --global user.name Plumbiu
          git add .
          git commit -m "build: target"
          git pull --rebase
      - name: Push target
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
